#!/bin/bash

#############################################################
# Vessel Image Inspection
#
# Purpose:
# This script performs an initial quality check of the vessel
# segmentation output generated by the M3PI preprocessing
# pipeline.
#
# Before quantitative vessel analysis, the vessel image should
# be inspected to determine whether it represents:
#
#   - a binary vessel mask (0 = background, 1 = vessel)
#   - probability values
#   - intensity-based vessel information
#
# This script checks:
#
#   1. Intensity range (minimum and maximum values)
#   2. Number of non-zero voxels
#   3. Total non-zero volume
#
# Software requirement:
#   FSL (fslstats)
#
# Author:
# Anuschka Bergmann
#
#############################################################


# ---------------------------
# Input vessel image
# ---------------------------

VESSEL_IMAGE="/Neurodata/M3PI/derivatives/Anuschka/00.sub-02_ses-7T_part-mag_T2starw_imgavg_preprocessed_vessels.nii.gz"


# ---------------------------
# Check that file exists
# ---------------------------

if [ ! -f "$VESSEL_IMAGE" ]; then
    echo "ERROR: Vessel image not found:"
    echo "$VESSEL_IMAGE"
    exit 1
fi


echo "Inspecting vessel image:"
echo "$VESSEL_IMAGE"
echo ""


# ---------------------------
# 1. Intensity range
# ---------------------------

echo "----------------------------------"
echo "1. Vessel intensity range"
echo "----------------------------------"

fslstats "$VESSEL_IMAGE" -R


# ---------------------------
# 2. Non-zero voxel count and volume
# ---------------------------

echo ""
echo "----------------------------------"
echo "2. Vessel voxel count and volume"
echo "----------------------------------"

fslstats "$VESSEL_IMAGE" -V


echo ""
echo "Inspection complete."

